### PR TITLE
AWS memcache rollbacked and introduced as own module

### PR DESCRIPTION
**Pull request by vladaGithub**

### CODE REVIEW

**Review by nazartm — COMMENTED** [review]
Do you think elasticcache/memcached will cause problems? I doubt we need duplicate

**Comment by vladaGithub** [comment]
> Do you think elasticcache/memcached will cause problems? I doubt we need duplicate

Can you try to switch to new elasticache/memcached in your PM PR branch and check? if its ok, I will remove: `../elasticache/main.tf `

**Comment by nazartm** [comment]
Merely changing the name causes the resources to be destroyed and recreated. However, this can be mitigated using the move clause. 

I tested using:

`moved {
  from = module.pm-elasticache-memcached-at1.aws_elasticache_cluster.elasticache
  to   = module.pm-elasticache-memcached-at1.aws_elasticache_cluster.memcached
}

moved {
  from = module.pm-elasticache-memcached-at1.aws_security_group.elasticache
  to   = module.pm-elasticache-memcached-at1.aws_security_group.memcached
}

moved {
  from = module.pm-elasticache-memcached-at1.aws_elasticache_subnet_group.subnet_group
  to   = module.pm-elasticache-memcached-at1.aws_elasticache_subnet_group.memcached
}`

And this results in no change and state is updated, and it can be removed afterwards.

**Review by nazartm — APPROVED** [review]
Remember to squash :)

**Comment by vladaGithub** [comment]
> Remember to squash :)

its one commit, but I will try ;-)

**Pull request merged**
